config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  resources :books do
    member do
      get :delete
    end
  end


  #get 'demo/index'
  #get ':controller(/:action(/:id))'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end  
  
  def new
    @book = Book.new
    @genres = ["Mystery", "Romance", "Science Fiction", "Fantasy", "Non-Fiction"]
    @genres.map{|k| [k,k]}
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book created successfully!"
      redirect_to(books_path)
    else
      render('new')
    end
  end

  def edit
    @book = Book.find(params[:id])
    @genres = ["Mystery", "Romance", "Science Fiction", "Fantasy", "Non-Fiction"]
    @defaultDate = @book.published_date.to_s
    @genres.map{|k| [k,k]}
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      flash[:notice] = "Book updated successfully!"
      redirect_to(book_path(@book))
    else
      render('edit')
    end
  end



  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book deleted successfully!"
    redirect_to(books_path)
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :genre, :price,:published_date)
  end
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  layout false
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_collection_helper.rb
module BookCollectionHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/views/books/delete.html.erb
<h2>Delete a Book</h2>
<%= form_for(@book, :method => 'delete') do |form| %>
    <p class="content">Are you sure you want to delete this book?</p>
    <p class="content">ID: <%=form.object.id%></p>
    <p class="content">Title: <%=form.object.title%></p>
    <%= form.submit("Delete Book")%>
    <%end%>

app/views/books/edit.html.erb
<h2 class='content'>Update a Book</h2>


<%= form_for(@book) do |form| %>  
    
      <%= form.label :title %> 
      <%= form.text_field(:title, value: @book.title.to_s) %>
  
      <%= form.label :author %> 
      <%= form.text_field(:author) %>
  
      <%= form.label :genre %>
      <%= form.select("genre", @genres, {index: nil}) %>
      <%#= form.text_field(:genre) %>
  
      <%= form.label :price %> 
      <%= form.number_field :price, step: :any %>

      <%= form.label :published_date%>
      <%= form.date_field(:published_date, :value => @book.published_date.to_s.to_date) %>     
      <%= form.submit("Update Book") %>


  <% end %> 

app/views/books/index.html.erb
<% if !flash[:notice].blank?%>
    <div>
        <%=flash[:notice]%>
    </div>
<%end%>

<div class="content">
    <h2>Books</h2>
    <table class="listing" summary="Book list">
    <% @books.each do |book| %>
        <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.genre %></td>
        <td><%= book.price %></td>
        <td><%= book.published_date %></td>
        <td class="actions">
            <%= link_to("Details", {:action => 'show', :id => book.id}, :class => 'action show') %>
            <%= link_to("Update", edit_book_path(book), :class => 'action edit') %>
            <%= link_to("Delete", delete_book_path(book), :class => 'action delete') %>
        </td>
        </tr>
    <%end%>
    </table>
</div>

app/views/books/new.html.erb
<h2 class='content'>Add a  new Book</h2>


<%= form_for(@book) do |form| %>  
    
      <%= form.label :title %> 
      <%= form.text_field(:title) %>
  
      <%= form.label :author %> 
      <%= form.text_field(:author) %>
  
      <%= form.label :genre %>
      <%= form.select("genre", @genres, {index: nil}) %>
      <%#= form.text_field(:genre) %>
  
      <%= form.label :price %> 
      <%= form.number_field :price, step: :any %>

      <%= form.label :published_date%> 
      <%= form.date_field(:published_date) %>     
      <%= form.submit("Create Book") %>


  <% end %>

app/views/books/show.html.erb
<% if !flash[:notice].blank?%>
    <div class="content">
        <%=flash[:notice]%>
    </div>
<%end%>

<div class="content">
  <h2>Book Details</h2>

  <table summary="Book detail view">
    <tr>
      <th>Title</th>
      <td><%= @book.title %></td>
    </tr>
    <tr>
      <th>Author</th>
      <td><%= @book.author %></td>
    </tr>
    <tr>
      <th>Genre</th>
      <td><%= @book.genre %></td>
    </tr>
    <tr>
      <th>Price</th>
      <td><%= @book.price %></td>
    </tr>
    <tr>
      <th>Date Published</th>
      <td><%= @book.published_date %></td>
    </tr>
  </table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookCms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header class='clearfix'>
  <div class="left-nav">
    <ul>
      <li><%= link_to('Home', {:action => 'index'}) %></li>
      <li><%= link_to("Add New Book", {:action => 'new'}) %></li>

  </div>
</header>

  <body>
    <%= yield %>
  </body>
</html>